SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 800

ROAD_MARGIN = 20
ROAD_WIDTH = SCREEN_WIDTH - (2 * ROAD_MARGIN)

TARGET_FPS = 60

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
BLUE = (0, 0, 255)
GREEN = (0, 255, 0)

PLAYER_IMAGE_PATH = "assets/player-image.png"
NPC_IMAGE_PATH = "assets/npc-image.png"
ROAD_IMAGE_PATH = "assets/background.png"

HIGH_SCORE_FILE_PATH = "highscore.txt"

ACCELERATION_CONSTANT = 0.1
BRAKING_CONSTANT = 0.7
MAX_SPEED = 20

PLACEHOLDER_CAR_WIDTH = 75
PLACEHOLDER_CAR_HEIGHT = 150

LANE_MARGIN = 5
TARGET_LANE_WIDTH = PLACEHOLDER_CAR_WIDTH + (2 * LANE_MARGIN)

NUM_LANES = ROAD_WIDTH // TARGET_LANE_WIDTH
LANE_WIDTH = ROAD_WIDTH // NUM_LANES

LANE_POSITIONS = []
lane_1_x_position = ROAD_MARGIN + (LANE_WIDTH // 2)
for i in range(NUM_LANES):
    LANE_POSITIONS.append(lane_1_x_position + (i * LANE_WIDTH))


MAX_NPCS = 5

NPC_MIN_SPEED = 7
NPC_MAX_SPEED = 10

NPC_SPAWN_INTERVAL = 1

PLAYER_Y_POS = SCREEN_HEIGHT - PLACEHOLDER_CAR_HEIGHT
PLAYER_START_X_POS = SCREEN_WIDTH / 2

HORIZONTAL_ACCELERATION_CONSTANT = 0.5
MAX_HORIZONTAL_SPEED = 10
